# This task list many ways to get status from your devices
- name: Get some status
  hosts: vqfx10k
  connection: local
  gather_facts: no

  roles:
    - Juniper.junos


  tasks:

#-
   - name: get lldp neighbor table
     juniper_junos_rpc:
        rpc: get-lldp-neighbors-information
        format: text
        #format: json
        #format: xml
     register: output

   - debug:
       msg: "{{output}}"

