# This task list many ways to get status from your devices
- name: Get some status v2
  hosts: vqfx10k
  connection: local
  gather_facts: no

  roles:
    - Juniper.junos


  tasks:

#-
   - name: Retrieve information from devices running Junos
     junos_get_facts:
     register: version

   - debug:
       msg: "{{version}}"

   - name: collect default set of facts and configuration
     junos_get_facts:
       gather_subset: config

